@startuml
activate Thread1
activate Thread2
activate Thread3


Thread1 -> Thread1: Sleep  7
activate Thread1
deactivate Thread1
Thread1 -> Thread1: Activity 2-3
activate Thread1
deactivate Thread1
Thread1 -> Monitor1: Notify
activate Monitor1
Thread1 -> Monitor2: Notify
activate Monitor2

Thread1 -> latch: countDown


Thread2 -> Monitor1: Acquire
Thread2 -> Thread2: Activity 3-5
activate Thread2
deactivate Thread2


Thread3 -> Monitor2: Acquire
Thread3 -> Thread3: Activity 4-6
activate Thread3
deactivate Thread3
Thread2 -> latch: countDown

Thread3 -> latch: countDown



Thread1 -> Thread1: Wait for Thread2
deactivate Thread2
Thread1 -> Thread1: Wait for Thread3
deactivate Thread3
deactivate Thread1


@enduml