@startuml

participant Main
participant ReadThread
participant WriteThread

Main -> ReadThread: new ReadThread()
activate ReadThread
Main -> WriteThread: new WriteThread()
activate WriteThread

Main -> ReadThread: conect(wt.getPipe())
ReadThread -> WriteThread: wt.getPipe()
activate WriteThread

ReadThread -> "PipedInputStream\n(Pipe)" as PI
WriteThread -> "PipedOutputStream\n(Pipe)" as PO

loop Communication Loop
    WriteThread -> PO: write(d)
    ReadThread -> PI: read()
    alt Data Available
        PI --> ReadThread: Data
        ReadThread -> Main: Print Data
    else No Data Available
        ReadThread -> PI: available()
    end
end

@enduml
